-- =========================================================
-- ICICI PRUDENTIAL DATA ENGINEERING PROJECT
-- DATABASE & SCHEMA SETUP
-- =========================================================

CREATE DATABASE IF NOT EXISTS ICICI_PRUDENTIAL;

USE DATABASE ICICI_PRUDENTIAL;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS MARTS;